######################################################################
# Automatically generated by qmake (3.0) Fri Nov 17 16:31:10 2017
######################################################################

TEMPLATE = app
TARGET = gui_form 
INCLUDEPATH += . /usr/include/qt4 /usr/include/qt4/QtGui 
LIBS += -L/usr/lib/x86_64-linux-gnu -lQtCore -lQtGui -lopencv_calib3d -lopencv_core -lopencv_highgui

# Input
HEADERS += gui_form.h
FORMS += gui_form.ui
SOURCES += main.cpp gui_form.cpp
