######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 21 18:48:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_gui_app.cpp
